### ISSUE TITLE
Unable to sign in - the user is not licensed for MAM

### ISSUE THREAD

**Issue by hank345** [msintuneappsdk/Chatr-Sample-Intune-iOS-App#52]
Hi,

I signed up for an Intunes trial licence (30 days), and now I'm trying to run this example app but the authentication does not seem to work. I'm getting this error message: 
**"The operation could not be completed because the user is not licensed for MAM."**

The error occurs after this is called in the LoginPage: 
`IntuneMAMEnrollmentManager.instance().loginAndEnrollAccount(nil)`

I double checked in the Microsoft Endpoint Manager Endpoint manager, and the user indeed has an Intune license.
Do you know what else can cause that error message?

Thanks,

Henrik

**Comment by hank345** [comment]
Ok, my bad. For some reason I missed issue #51. I will try to perform the steps suggested there, and let you know if that works. Kind of a misleading error message though?

**Comment by hank345** [comment]
Hi Kyle, 
For some reason today, it actually started working. Now the problem is that I'm not exactly sure why :/

But earlier, yes I was prompted for credentials.
I'm on a 30 day trial at the moment. Since I started testing the user I'm using has always had a license.
I first started with my own app based on what I could find in the documentation, but then switched to your example (with the same user).

I'm sorry I could not give more specific details.

**Comment by parveen-bhatia** [comment]
I am facing same issue. Authentication using MSAL (1.1.17) works fine. But getting error on enrollment with intune using `loginAndEnrollAccount`.
Enrollment is working fine after reseting the iOS simulator. But it's hard for users to reset the device.

@Kyle-Reis can you please suggest any workaround or do know in which version it would be fixed.

**Comment by kapilntt** [comment]
Hi,

I am also having the same problem and resetting simulator is not helping either. 
Details as follows:

The setup:
* User has following Intune licenses 
** Intune -> Microsoft Intune
** Enterprise Mobility + Security E5 -> Microsoft Intune
* The user is on 30 day trial Intune instance
* Nuget Package: Microsoft.Intune.MAM.Xamarin.iOS - 15.0.0.1

This is what user actions and observes:
* App starting in iOS 15.0 simulator 
* Click on Login
* For very first time, user is prompted for user+password
* Upon auth window closing, a message is displayed - "Enrollment Failed", "The operation could not be completed because user is not licensed for MAM"

What I have tried so far but didn't help
* I have created a new user with new license applied but still gets the same message
* Reset the emulator 

Please let me know if I have to report this as a new issue.

**Comment by SameerK-MSFT** [comment]
I am having the same issue.

**Comment by thomasarogers** [comment]
Anyone resolved this since?

**Comment by lukeashton4** [comment]
I am facing the same issue here too.

**Comment by lukeashton4** [comment]
@Kyle-Reis @msft-neiljac Can this be re-opened or should I open a new support case? It looks like lots of people are encountering the same problem. Thanks
